### ISSUE TITLE
Doesn't work in VS2022 Preview?

### ISSUE THREAD

**Issue by mejobloggs-cw** [mrlacey/ErrorHelper#16]
Hi there,

When I right click on and error and select any option ErrorHelper option (copy/search etc), no action happens.

If I paste, no error has been copied. It pastes what was already in my clipboard before clicking "copy error"

Probably this is because I am on Preview?

In the Error Helper output window there is no logs or anything to provide you

Error Helper   2.8
Microsoft Visual Studio Community 2022
Version 17.10.0 Preview 6.0

**Comment by mrlacey** [comment]
It should work on any version of Visual Studio where it can be installed.
If the menu is shown, it should work.

I'll investigate.

**Comment by mrlacey** [comment]
I've just released an updated version to the marketplace (v2.8.2) and this adds logging to the output pane and shows a message on the status bar if the description was blank.
There already was code to report an exception.
Can you try with the new version and see if you get any output.

**Comment by mrlacey** [comment]
It looks like a bug in the latest preview version of VS.
It always returns an empty string (and says it was successful) when requesting the text from the error item.
I'm escalating to MS.

**Comment by mejobloggs-cw** [comment]
Nice, "Under Investigation" already. Thanks for that!

**Comment by mejobloggs-cw** [comment]
Actually.... I'm on "Version 17.11.0 Preview 1.0" and it still doesn't work 🤔

I will try reinstalling the extension

**Comment by mejobloggs-cw** [comment]
Yeah still not working

**Comment by mrlacey** [comment]
will investigate what happened to v2.8.2

**Comment by mrlacey** [comment]
> will investigate what happened to v2.8.2

The version numbers somehow got messed up. 2.8.2 reports as 2.8.1 in the marketplace - I can't work out why but there's no meaningful difference between the two versions, only minor differences in the log output.
